In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/mac/Desktop/water_pump_log.txt")

In [5]:
df.head()

deviceId  waterPumpTypeId  pumpOutput  power  temperature  longitude  \
0      1000                1        1988    882           35      122.4   
1      1000                1        2235    954           36      124.4   
2      1000                1        1835    937           36      120.4   
3      1000                1        2165    844           37      117.4   
4      1000                1        2129    947           37      117.4   

   latitude        logTime  productionDate  currentDateRecord  
0      40.9  1565706085685            2017           20190813  
1      39.9  1565706085685            2017           20190813  
2      44.9  1565706085686            2017           20190813  
3      41.9  1565706085686            2017           20190813  
4      42.9  1565706085686            2017           20190813

In [8]:
frame = pd.DataFrame(df, columns=['waterPumpTypeId', 'pumpOutput', 'power'])

In [30]:
frame['label']= 0
frame.loc[frame['waterPumpTypeId'] == 5 ,'label'] = 1

In [35]:
frame2 = pd.DataFrame(frame, columns=['pumpOutput', 'power', 'label'])
frame2.describe()

pumpOutput         power         label
count  14399.000000  14399.000000  14399.000000
mean    1100.152441    492.587124      0.206542
std      769.836447    364.362736      0.404838
min      300.000000    100.000000      0.000000
25%      508.000000    238.000000      0.000000
50%      744.000000    309.000000      0.000000
75%     2007.500000    903.000000      0.000000
max     2499.000000   1169.000000      1.000000

In [36]:
X_frame = pd.DataFrame(frame2, columns=['pumpOutput', 'power'])

In [39]:
X = X_frame.values

In [40]:
X

array([[1988,  882],
       [2235,  954],
       [1835,  937],
       ...,
       [ 538,  243],
       [ 507,  273],
       [ 524,  275]])

In [41]:
y_frame = pd.DataFrame(frame2, columns=[ 'label'])
y = y_frame.values

In [42]:
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [43]:
import numpy as np
import matplotlib.pyplot as plt

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [46]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
log_reg.score(X_train, y_train)

0.8950828780442633

In [48]:
log_reg.score(X_test, y_test)

0.8958333333333334

In [49]:
log_reg.predict([[1988,  882]])

array([0])

In [56]:
log_reg.predict([[510,287]])

array([1])

In [57]:
frame2[frame2['label'] == 1].head()

pumpOutput  power  label
11425         508    296      1
11426         559    246      1
11427         569    280      1
11428         540    256      1
11429         507    249      1